# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('addressid', models.BigAutoField(db_column='AddressID', primary_key=True, serialize=False)),
                ('street', models.CharField(blank=True, db_column='Street', max_length=255, null=True)),
                ('astate', models.CharField(blank=True, db_column='aState', max_length=255, null=True)),
                ('zip', models.CharField(blank=True, db_column='Zip', max_length=255, null=True)),
            ],
            options={
                'db_table': 'address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Billinginformation',
            fields=[
                ('billinginformationid', models.BigAutoField(db_column='BillingInformationID', primary_key=True, serialize=False)),
                ('creditcardnumber', models.IntegerField(blank=True, db_column='CreditCardNumber', null=True)),
                ('expirationdate', models.DateField(blank=True, db_column='ExpirationDate', null=True)),
            ],
            options={
                'db_table': 'billinginformation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cartid', models.BigAutoField(db_column='CartID', primary_key=True, serialize=False)),
                ('numberofitems', models.IntegerField(blank=True, db_column='NumberOfItems', null=True)),
                ('totalcost', models.FloatField(blank=True, db_column='TotalCost', null=True)),
                ('shippingcost', models.FloatField(blank=True, db_column='ShippingCost', null=True)),
            ],
            options={
                'db_table': 'cart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cartedproduct',
            fields=[
                ('cartedproductid', models.BigAutoField(db_column='CartedProductID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'cartedproduct',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerid', models.BigAutoField(db_column='CustomerID', primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=255, null=True)),
                ('cname', models.CharField(blank=True, db_column='cName', max_length=255, null=True)),
                ('pass_field', models.CharField(blank=True, db_column='Pass', max_length=255, null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Neworder',
            fields=[
                ('neworderid', models.BigAutoField(db_column='NewOrderID', primary_key=True, serialize=False)),
                ('orderdate', models.DateField(blank=True, db_column='OrderDate', null=True)),
            ],
            options={
                'db_table': 'neworder',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productid', models.BigAutoField(db_column='ProductID', primary_key=True, serialize=False)),
                ('shippingcost', models.FloatField(blank=True, db_column='ShippingCost', null=True)),
                ('productname', models.CharField(blank=True, db_column='ProductName', max_length=255, null=True)),
                ('color', models.CharField(blank=True, db_column='Color', max_length=255, null=True)),
                ('price', models.FloatField(blank=True, db_column='Price', null=True)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staffid', models.BigAutoField(db_column='StaffID', primary_key=True, serialize=False)),
                ('staffname', models.CharField(blank=True, db_column='StaffName', max_length=255, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=255, null=True)),
                ('wage', models.IntegerField(blank=True, db_column='Wage', null=True)),
                ('spassword', models.CharField(blank=True, db_column='sPassword', max_length=255, null=True)),
            ],
            options={
                'db_table': 'staff',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wholesaler',
            fields=[
                ('wholesalerid', models.BigAutoField(db_column='WholesalerID', primary_key=True, serialize=False)),
                ('website', models.CharField(blank=True, db_column='Website', max_length=255, null=True)),
                ('wholesalername', models.CharField(blank=True, db_column='WholesalerName', max_length=255, null=True)),
                ('wholesalerphone', models.CharField(blank=True, db_column='WholesalerPhone', max_length=255, null=True)),
                ('wholesalerlocation', models.CharField(blank=True, db_column='WholesalerLocation', max_length=255, null=True)),
            ],
            options={
                'db_table': 'wholesaler',
                'managed': False,
            },
        ),
    ]
